version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  install-and-test:
    docker:
      - image: circleci/node:15.4
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - run:
          name: Copy tests results for storing
          command: |
            mkdir ~/test-results
            cp test-results.xml ~/test-results/
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results
workflows:
  everything:
    jobs:
      - build-and-test